project:
  type: website

  

website:    
  title: "Jeremy's Webpage"
  google-analytics: G-CY8CSYZB1B
  page-footer:
    center:
      - icon: linkedin
        href: https://www.linkedin.com/in/jeremy-lewi-600aaa8/
      - icon: twitter
        href: https://twitter.com/jeremylewi
      - icon: github
        href: https://github.com/jlewi
  twitter-card:
     creator: "@jeremylewi"
     site: "@jeremylewi"
     card-style: summary_large_image
  site-url: "https://lewi.us/"
  description: "Jeremy Lewi's Webpage."
  repo-url: https://github.com/jlewi/notes
  repo-actions: [edit]
  repo-branch: main
  navbar:
    title: false
    background: dark
    pinned: false
    collapse: false
    left:
      - href: index.qmd
        text: Home
      - text: OSS
        file: oss/opensource.qmd
      - about.qmd
      - href: hire.qmd
        text: Hire Me
      - text: Talks 
        file: talks.qmd
      - href: notes/index.qmd
        text: Notes

execute:
  # To Render on Netlify https://quarto.org/docs/publishing/netlify.html#freezing-computations
  # we need to freeze computations in R, Python, and Julia.
  # This shouldn't be an issue since we don't use that.
  freeze: auto
  eval: false


format:
  html:
    theme: darkly
    css: styles.css
    toc: true