project:
  type: website

  

website:
  title: "Jeremy's Notes"
  google-analytics: G-CY8CSYZB1B
  navbar:
    title: false
    background: dark
    pinned: false
    collapse: false
    left:
      - href: index.qmd
        text: Home
      - about.qmd

execute:
  # To Render on Netlify https://quarto.org/docs/publishing/netlify.html#freezing-computations
  # we need to freeze computations in R, Python, and Julia.
  # This shouldn't be an issue since we don't use that.
  freeze: auto
  eval: false


format:
  html:
    theme: darkly
    css: styles.css
    toc: true



